const actionTypes = {
    CYNIC_ES_ACCURACY_PENDING: "CYNIC_ES_ACCURACY_PENDING",
    CYNIC_ES_ACCURACY_REJECTED: "CYNIC_ES_ACCURACY_REJECTED",
    CYNIC_ES_ACCURACY_FULFILLED: "CYNIC_ES_ACCURACY_FULFILLED",

    FN_HASHTRACKING_PENDING: "FN_HASHTRACKING_PENDING",
    FN_HASHTRACKING_REJECTED: "FN_HASHTRACKING_REJECTED",
    FN_HASHTRACKING_FULFILLED: "FN_HASHTRACKING_FULFILLED",
    FN_CYNIC_ES_COMMENTS_PENDING: "FN_CYNIC_ES_COMMENTS_PENDING",
    FN_CYNIC_ES_COMMENTS_REJECTED: "FN_CYNIC_ES_COMMENTS_REJECTED",
    FN_CYNIC_ES_COMMENTS_FULFILLED: "FN_CYNIC_ES_COMMENTS_FULFILLED",
    FN_SAVE_ES_COMMENTS_PENDING: "FN_SAVE_ES_COMMENTS_PENDING",
    FN_SAVE_ES_COMMENTS_REJECTED: "FN_SAVE_ES_COMMENTS_REJECTED",
    FN_SAVE_ES_COMMENTS_FULFILLED: "FN_SAVE_ES_COMMENTS_FULFILLED",
    FN_ES_COMMENTS_UNIQUE_PENDING: "FN_ES_COMMENTS_UNIQUE_PENDING",
    FN_ES_COMMENTS_UNIQUE_REJECTED: "FN_ES_COMMENTS_UNIQUE_REJECTED",
    FN_ES_COMMENTS_UNIQUE_FULFILLED: "FN_ES_COMMENTS_UNIQUE_FULFILLED",

    FP_HASHTRACKING_PENDING: "FP_HASHTRACKING_PENDING",
    FP_HASHTRACKING_REJECTED: "FP_HASHTRACKING_REJECTED",
    FP_HASHTRACKING_FULFILLED: "FP_HASHTRACKING_FULFILLED",
    FP_CYNIC_ES_COMMENTS_PENDING: "FP_CYNIC_ES_COMMENTS_PENDING",
    FP_CYNIC_ES_COMMENTS_REJECTED: "FP_CYNIC_ES_COMMENTS_REJECTED",
    FP_CYNIC_ES_COMMENTS_FULFILLED: "FP_CYNIC_ES_COMMENTS_FULFILLED",
    FP_SAVE_ES_COMMENTS_PENDING: "FP_SAVE_ES_COMMENTS_PENDING",
    FP_SAVE_ES_COMMENTS_REJECTED: "FP_SAVE_ES_COMMENTS_REJECTED",
    FP_SAVE_ES_COMMENTS_FULFILLED: "FP_SAVE_ES_COMMENTS_FULFILLED",
    FP_ES_COMMENTS_UNIQUE_PENDING: "FP_ES_COMMENTS_UNIQUE_PENDING",
    FP_ES_COMMENTS_UNIQUE_REJECTED: "FP_ES_COMMENTS_UNIQUE_REJECTED",
    FP_ES_COMMENTS_UNIQUE_FULFILLED: "FP_ES_COMMENTS_UNIQUE_FULFILLED",
    
}
export default actionTypes;